--- 
:application_name: CAPA
:page_title_prefix: CAPA
:logo: capa_logo.png
:home_link: http://capa.concord.org/
:stylesheet: capa
:external_otrunk_activities_title: Assessment
:show_external_otrunk_activities: true
:hide_activities: true
:hide_models: true
:disable_anonymous_seeing: true
