development:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  host: localhost
  database: development
  username: root
  password: 

test:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  host: localhost
  database: test
  username: root
  password: 

production:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  host: localhost
  database: production
  username: root
  password: 

sunflower:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  host: database.concord.org
  username: rails
  password: 
  database: sunflower

remote:
  adapter: <% if RUBY_PLATFORM =~ /java/ %>jdbcmysql<% else %>mysql<% end %>
  encoding: utf8
  host: 
  database: 
  username: 
  password: 
  table_prefix: 