--- 
:application_name: Do It Yourself
:page_title_prefix: DIY
:logo: diy_logo.gif
:home_link: http://www.concord.org/
:stylesheet: diy
:external_otrunk_activities_title: Concord Activities
:show_external_otrunk_activities: true
:hide_activities: false
:hide_models: false
