--- 
:application_name: Evolution Readiness
:page_title_prefix: ER
:logo: er-logo.png
:home_link: http://www.concord.org/
:stylesheet: er
:external_otrunk_activities_title: Activities
:show_external_otrunk_activities: true
:hide_activities: true
:hide_models: true
:anonymous_run_style: preview