--- 
:application_name: Electron Technologies DIY
:page_title_prefix: ET DIY
:logo: diy_logo.gif
:home_link: http://et.concord.org/
:stylesheet: diy
:external_otrunk_activities_title: Concord Activities
:show_external_otrunk_activities: true
:hide_activities: true
:hide_models: true
:anonymous_run_style: preview