--- 
:application_name: Geniquest DIY
:page_title_prefix: Geniquest
:logo: geniquest_64x64.png
:home_link: http://www.concord.org/
:stylesheet: geniquest
:external_otrunk_activities_title: Activities
:show_external_otrunk_activities: true
:cache_external_otrunk_activities: false
:hide_activities: true
:hide_models: true
# run style options are: savedata, view, nobundles, preview, norun
:anonymous_run_style: preview