--- 
:application_name: ITSI-SU Do It Yourself
:page_title_prefix: ITSI-SU DIY
:logo: itsi_su_logo.gif
:home_link: http://itsisu.diy.concord.org/
:stylesheet: itsi
:external_otrunk_activities_title: External OTrunk Activities
:show_external_otrunk_activities: false
:hide_activities: false
:hide_models: false
# run style options are: savedata, view, nobundles, preview, norun
:anonymous_run_style: preview
# show an activity preview image? (usually just a generic model image)
:hide_activity_image: true
:enable_career_stem: true
:activity_report_template_url: https://github.com/concord-consortium/itsisu_reports/raw/master/reports/diy-full-report.otml
:activity_report_template_name: DIY default activity report template
:external_otrunk_activity_report_template_url: https://github.com/concord-consortium/itsisu_reports/raw/master/reports/pre-test-report.otml
:external_otrunk_activity_report_template_name: Pre and Post test report template
:help_email: itsi-su-support@concord.org
