--- 
:application_name: JASON Academy Do It Yourself
:page_title_prefix: JASON DIY
:logo: teemss_logo.png
:home_link: http://teemss.concord.org/
:stylesheet: diy
# run style options are: savedata, view, nobundles, preview, norun
:anonymous_run_style: preview