--- 
:application_name: LOOPS Do It Yourself
:page_title_prefix: LOOPS DIY
:logo: diy_logo.gif
:home_link: http://loops.concord.org/
:stylesheet: loops
:external_otrunk_activities_title: Activities
:show_external_otrunk_activities: true
:cache_external_otrunk_activities: true
:hide_activities: true
:hide_models: true
# run style options are: savedata, view, nobundles, preview, norun
:anonymous_run_style: preview
