--- 
:application_name: Alaskan Scientists of the Future DIY
:page_title_prefix: ASF DIY
:logo: onr.png
:home_link: http://onr.navy.mil/
:stylesheet: onr
# run style options are: savedata, view, nobundles, preview, norun
:anonymous_run_style: preview
