all:
    inject_view: true
    warn_severity: 3
    critical_severity: 7
    warn_query_count: 20
    critical_query_count: 50
        
development:
    enabled: false
    
production:
    enabled: false
    
test:
    enabled: false