--- 
:application_name: Universal Design in Science Education
:page_title_prefix: UDL
:logo: udl-logo.gif
:home_link: http://udl.concord.org/
:stylesheet: udl
:external_otrunk_activities_title: Unit
:show_external_otrunk_activities: true
:hide_activities: true
:hide_models: true
# run style options are: savedata, view, nobundles, preview, norun
:anonymous_run_style: preview